### ISSUE TITLE
[Feature discussion] - Social buttons

### ISSUE THREAD

**Issue by kylemclaren** [chadokruse/meteor-coming-soon-email-capture#1]
Hi @chadokruse ,

Thanks for this repo, it's really coming in handy!

I'm new to Meteor and I'm struggling to add social buttons (namely Facebook Like and Twitter Follow).

I've tried Googling to no avail and this post on stackoverlfow hasn't helped me either.
http://stackoverflow.com/questions/18868345/embed-social-sharing-buttons-in-a-meteor-app/18872168?noredirect=1#18872168

My app just crashes and throws errors.

I'll continue to try and figure it out but would be great if you could add this feature if you know how.

Looking forward to your comments.

**Comment by chadokruse** [comment]
Hi @KyleSA  - sorry for the delay. I think this would indeed be a great addition. Any luck?

I unfortunately won't be able to get to this any time in the near future, but in case it helps, the [Telescope](http://demo.telesc.pe/) demo app has the sharing feature built in.

**Comment by kylemclaren** [comment]
No probs, looks like they've implemented [Sharrre](http://sharrre.com).

I'll give it a crack. Thanks!
